#!/usr/bin/env sh
set -e

# Path to the options file generated by Home Assistant Supervisor
OPTIONS_FILE="/data/options.json"

if [ -f "$OPTIONS_FILE" ]; then
    echo "[Info] Reading configuration options from $OPTIONS_FILE"
    
    # Try using python3 or python to parse the options
    PYTHON_CMD=""
    if command -v python3 >/dev/null 2>&1; then
        PYTHON_CMD="python3"
    elif command -v python >/dev/null 2>&1; then
        PYTHON_CMD="python"
    fi

    if [ -n "$PYTHON_CMD" ]; then
        eval $($PYTHON_CMD -c '
import json, sys
try:
    with open("/data/options.json") as f:
        config = json.load(f)
    for k, v in config.items():
        if v is not None:
            val = str(v)
            val_escaped = val.replace("'\''", "'\''\\'\'''\''")
            print(f"export {k.upper()}=\x27{val_escaped}\x27")
except Exception as e:
    sys.stderr.write(f"Error parsing options.json: {e}\n")
')
    else
        echo "[Warning] Python not found, unable to parse options.json. Using default environment."
    fi
else
    echo "[Warning] No options file found at $OPTIONS_FILE. Using default environment."
fi

# Ensure uv is globally accessible (in case it is installed under root-only paths or custom directories)
if [ ! -f "/usr/local/bin/uv" ]; then
    PYTHON_CMD=""
    if command -v python3 >/dev/null 2>&1; then
        PYTHON_CMD="python3"
    elif command -v python >/dev/null 2>&1; then
        PYTHON_CMD="python"
    fi

    if [ -n "$PYTHON_CMD" ]; then
        $PYTHON_CMD -c '
import os, sys, shutil
print("[Info] uv not found in PATH. Searching filesystem...")
found = []
skip_dirs = {"/proc", "/sys", "/dev", "/data", "/photon/data", "/photon/photon_db"}
for root, dirs, files in os.walk("/"):
    # prune skipped dirs
    if any(root.startswith(d) for d in skip_dirs):
        dirs[:] = []
        continue
    if "uv" in files:
        p = os.path.join(root, "uv")
        if os.path.isfile(p) and os.access(p, os.X_OK) and p != "/usr/local/bin/uv":
            found.append(p)
            print(f"[Info] Found executable uv at: {p}")

if found:
    src = found[0]
    dst = "/usr/local/bin/uv"
    print(f"[Info] Copying {src} to {dst} for global access...")
    try:
        shutil.copy2(src, dst)
        os.chmod(dst, 0o755)
        print("[Info] Successfully made uv globally accessible.")
    except Exception as e:
        sys.stderr.write(f"Failed to copy uv: {e}\n")
else:
    print("[Warning] Could not find executable \x27uv\x27 binary in filesystem.")
    print("[Debug] Searching entire filesystem for any file containing \x27uv\x27:")
    for root, dirs, files in os.walk("/"):
        if any(root.startswith(d) for d in ["/proc", "/sys", "/dev", "/data", "/photon/data", "/photon/photon_db"]):
            dirs[:] = []
            continue
        for f in files:
            if "uv" in f:
                p = os.path.join(root, f)
                try:
                    stat = os.stat(p)
                    print(f"File: {p} | Size: {stat.st_size} | Mode: {oct(stat.st_mode)}")
                except Exception as e:
                    print(f"File: {p} (Error reading: {e})")
'
    else
        echo "[Warning] Python not found, skipping uv search."
    fi

    # If the Python search failed to find and copy uv, download it using the official installer
    if [ ! -f "/usr/local/bin/uv" ]; then
        echo "[Info] uv still not found. Downloading and installing uv..."
        export UV_INSTALL_DIR="/usr/local/bin"
        if command -v curl >/dev/null 2>&1; then
            curl -LsSf https://astral.sh/uv/install.sh | sh
        elif command -v wget >/dev/null 2>&1; then
            wget -qO- https://astral.sh/uv/install.sh | sh
        else
            echo "[Error] Neither curl nor wget is found. Cannot download uv."
            exit 1
        fi
        
        # Verify it was successfully installed
        if [ -f "/usr/local/bin/uv" ]; then
            chmod +x /usr/local/bin/uv
            echo "[Info] Successfully installed uv to /usr/local/bin/uv."
        else
            echo "[Error] uv installation failed."
            exit 1
        fi
    fi
fi

# Ensure persistent /data/photon_db directory exists and has permissive permissions
echo "[Info] Setting permissions on persistent storage..."
mkdir -p /data/photon_db
chmod 777 /data/photon_db
if [ -d "/data/photon_db" ]; then
    chmod -R 777 /data/photon_db 2>/dev/null || true
fi

# Symlink /photon/data to /data/photon_db so that Photon stores its database in the persistent HA volume
if [ -d "/photon/data" ] && [ ! -L "/photon/data" ]; then
    echo "[Info] Moving existing data from /photon/data to /data/photon_db"
    cp -rp /photon/data/* /data/photon_db/ 2>/dev/null || true
    rm -rf /photon/data
fi

if [ ! -L "/photon/data" ]; then
    echo "[Info] Linking /photon/data to persistent /data/photon_db"
    ln -s /data/photon_db /photon/data
fi


# Find the original entrypoint script of the base image
ENTRYPOINT_PATH="/photon/entrypoint.sh"
if [ ! -f "$ENTRYPOINT_PATH" ]; then
    if [ -f "/entrypoint.sh" ]; then
        ENTRYPOINT_PATH="/entrypoint.sh"
    elif command -v entrypoint.sh >/dev/null 2>&1; then
        ENTRYPOINT_PATH=$(command -v entrypoint.sh)
    else
        echo "[Error] Could not find the original entrypoint.sh script in the base image."
        exit 1
    fi
fi

# Make sure the original entrypoint script is executable
chmod +x "$ENTRYPOINT_PATH" 2>/dev/null || true

# Hand over execution to the original entrypoint script of the base image
echo "[Info] Starting original entrypoint: $ENTRYPOINT_PATH"
exec "$ENTRYPOINT_PATH" "$@"
