#!/usr/bin/env sh
set -e

# Path to the options file generated by Home Assistant Supervisor
OPTIONS_FILE="/data/options.json"

if [ -f "$OPTIONS_FILE" ]; then
    echo "[Info] Reading configuration options from $OPTIONS_FILE"
    
    # Try using python3 or python to parse the options
    PYTHON_CMD=""
    if command -v python3 >/dev/null 2>&1; then
        PYTHON_CMD="python3"
    elif command -v python >/dev/null 2>&1; then
        PYTHON_CMD="python"
    fi

    if [ -n "$PYTHON_CMD" ]; then
        eval $($PYTHON_CMD -c '
import json, sys
try:
    with open("/data/options.json") as f:
        config = json.load(f)
    for k, v in config.items():
        if v is not None:
            val = str(v)
            val_escaped = val.replace("'\''", "'\''\\'\'''\''")
            print(f"export {k.upper()}=\x27{val_escaped}\x27")
except Exception as e:
    sys.stderr.write(f"Error parsing options.json: {e}\n")
')
    else
        echo "[Warning] Python not found, unable to parse options.json. Using default environment."
    fi
else
    echo "[Warning] No options file found at $OPTIONS_FILE. Using default environment."
fi

# Ensure uv is globally accessible (in case it is installed under /root/.local/bin)
if ! command -v uv >/dev/null 2>&1; then
    echo "[Info] uv not found in PATH. Searching for uv binary..."
    FOUND_UV=$(find / -name uv -type f 2>/dev/null | head -n 1)
    if [ -n "$FOUND_UV" ]; then
        echo "[Info] Found uv at $FOUND_UV. Copying to /usr/local/bin/uv for global accessibility..."
        cp "$FOUND_UV" /usr/local/bin/uv
        chmod +x /usr/local/bin/uv
    else
        echo "[Warning] Could not find uv binary in the container."
    fi
else
    # Even if uv is in PATH for root, it might be in a root-restricted directory (like /root/.local/bin).
    # Let's ensure it is copied to /usr/local/bin/uv so the non-root 'photon' user can execute it.
    UV_CURRENT=$(command -v uv)
    case "$UV_CURRENT" in
        /root/*)
            echo "[Info] uv is in root-only path ($UV_CURRENT). Copying to /usr/local/bin/uv..."
            cp "$UV_CURRENT" /usr/local/bin/uv
            chmod +x /usr/local/bin/uv
            ;;
    esac
fi

# Ensure persistent /data/photon_db directory exists and has permissive permissions
echo "[Info] Setting permissions on persistent storage..."
mkdir -p /data/photon_db
chmod 777 /data/photon_db
if [ -d "/data/photon_db" ]; then
    chmod -R 777 /data/photon_db 2>/dev/null || true
fi

# Symlink /photon/data to /data/photon_db so that Photon stores its database in the persistent HA volume
if [ -d "/photon/data" ] && [ ! -L "/photon/data" ]; then
    echo "[Info] Moving existing data from /photon/data to /data/photon_db"
    cp -rp /photon/data/* /data/photon_db/ 2>/dev/null || true
    rm -rf /photon/data
fi

if [ ! -L "/photon/data" ]; then
    echo "[Info] Linking /photon/data to persistent /data/photon_db"
    ln -s /data/photon_db /photon/data
fi


# Find the original entrypoint script of the base image
ENTRYPOINT_PATH="/photon/entrypoint.sh"
if [ ! -f "$ENTRYPOINT_PATH" ]; then
    if [ -f "/entrypoint.sh" ]; then
        ENTRYPOINT_PATH="/entrypoint.sh"
    elif command -v entrypoint.sh >/dev/null 2>&1; then
        ENTRYPOINT_PATH=$(command -v entrypoint.sh)
    else
        echo "[Error] Could not find the original entrypoint.sh script in the base image."
        exit 1
    fi
fi

# Make sure the original entrypoint script is executable
chmod +x "$ENTRYPOINT_PATH" 2>/dev/null || true

# Hand over execution to the original entrypoint script of the base image
echo "[Info] Starting original entrypoint: $ENTRYPOINT_PATH"
exec "$ENTRYPOINT_PATH" "$@"
